name: Deploy new script

on:
  push:
      branches:
        - 'release/v**'

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Checkout to repo'
      uses: actions/checkout@v2
    - name: Run az shell script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          .github/helpers/deploy.sh