name: Deploy new script

on:
  push:
      branches:
        - 'release/v**'

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install IoT Extension
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az extension add --name azure-iot --yes
    
    - name: Send new message to device
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az iot device c2d-message send -d testdevice -n kevworkshop --data '{"release": "release/v0.1.0"}'