name: Deploy new script

on:
  push:
      branches:
        - 'release/v**'

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run az shell script
      run: sh .github/helpers/deploy.sh